name: PR Validator

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/setup-node@v4
        name: Install Node.js
        with:
          node-version: 21
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: latest
          run_install: true
      - uses: oven-sh/setup-bun@v1
        name: Install Bun
        with:
          bun-version: latest
      - run: pnpm lint
      - run: pnpm format:check
      - run: bun test
