name: PR Validator

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: latest
      - uses: oven-sh/setup-bun@v1
        name: Install Bun
        with:
          version: latest
      - run: pnpm install --frozen-lockfile
      - run: bun run lint
      - run: bun run format:check
      - run: bun run test:ci
