name: PR Validator

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  validate:
    runs-on: ubuntu-latest
    # services:
    #   postgres:
    #     image: postgres
    #     env:
    #       POSTGRES_PASSWORD: test
    #       POSTGRES_DB: test-db
    #     ports:
    #       - 5432:5432
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/setup-node@v4
        name: Install Node.js
        with:
          node-version: 21
      - uses: oven-sh/setup-bun@v1
        name: Install Bun
        with:
          bun-version: latest
      - run: bun install
      - run: bun lint
      - run: npm run format:check
      - run: bun test
